name: dfa-elm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.4
  - torchvision=0.15
  - torchaudio=2.0
  - cudatoolkit=11.7  
  - numpy=1.21
  - scipy=1.8 
  - scikit-learn=1.0
  - imbalanced-learn=0.8
  - matplotlib=3.5
  - seaborn=0.11
  - pandas=1.3
  - pyedflib=0.1.20
  - mne=1.0
  - pywavelets=1.1
  - tqdm=4.62
  - pyyaml=6.0
  - joblib=1.0
  - pip
  - pip:
    - -r requirements.txt
